parameters:
    fungio.dataexporter.class: Fungio\DataExporterBundle\Service\DataExporter

services:
    fungio.dataexporter:
        class: "%fungio.dataexporter.class%"
        public: true
        shared: false
        arguments:
          - '@phpexcel'
